### ISSUE TITLE
Can't use the Transitions ?

### ISSUE THREAD

**Issue by Caesarovich** [marcusstenbeck/remotion-transition-series#3]
Hi,
It seems like you may have forgotten to export all the transitions "Slide, Pan, etc...".

So it works well to clone your repo and fiddle with it. But we can't import them inside an existing project to effectively using it as a lib.

Or maybe I'm missing something ? 🤔

**Comment by marcusstenbeck** [comment]
@Caesarovich The suggested approach is to copy and paste the code into your own repository. :)

**Comment by Caesarovich** [comment]
Ok I see, that's what I ended up doing.

It just feels a bit off having to install your library but needing to copy-paste the other half of it.

Well that's just my POV. Thanks anyway for the great work 👍❤️

**Comment by marcusstenbeck** [comment]
I understand, the point is to avoid having the npm package contain more than the minimally needed code.
