### ISSUE TITLE
Previous Sequence Does Not Exit?

### ISSUE THREAD

**Issue by btahir** [marcusstenbeck/remotion-transition-series#5]
Cool project! I tried setting up the basic example with Circular Wipe but seems the Hello does not go away when we add Transition. It works fine if you take Transition out. Is this broken because of new changes to Remotion 4 and how it handles Series? 

Here's a video of what I'm seeing. Any advice on how to fix is appreciated.

https://github.com/marcusstenbeck/remotion-transition-series/assets/10962432/5def93d4-816c-4448-8c22-dc31fda5a03d

**Comment by btahir** [comment]
OK - I think I figured it out. If I added a background color it did overwrite the old sequence!

**Comment by marcusstenbeck** [comment]
Oh, yes, if it's transparent the old will be visible. Glad you figure it out!
