### ISSUE TITLE
Example for multiple Transitions?

### ISSUE THREAD

**Issue by btahir** [marcusstenbeck/remotion-transition-series#6]
Sorry for piling on but wondering if there is a toy example I can see for multiple Transitions. If I do a loop with more than one Transition it seems only the last Transition is respected?

```
<AbsoluteFill
			style={{fontFamily}}
			className={`bg-black text-white items-center justify-center p-4`}
		>
			<TransitionSeries>
				<TransitionSeries.Sequence durationInFrames={30}>
					<div className="text-7xl flex justify-center items-center w-full h-full bg-black">
						First Page
					</div>
				</TransitionSeries.Sequence>
				<TransitionSeries.Transition
					durationInFrames={30}
					transitionComponent={LinearWipe}
				/>
				<TransitionSeries.Sequence durationInFrames={30}>
					<div className="text-7xl flex justify-center items-center w-full h-full bg-black">
						Second Page
					</div>
				</TransitionSeries.Sequence>
				<TransitionSeries.Transition
					durationInFrames={30}
					transitionComponent={CircularWipe}
				/>
				<TransitionSeries.Sequence durationInFrames={30}>
					<div className="text-7xl flex justify-center items-center w-full h-full bg-black">
						Third Page
					</div>
				</TransitionSeries.Sequence>
			</TransitionSeries>
		</AbsoluteFill>
```

Result

https://github.com/marcusstenbeck/remotion-transition-series/assets/10962432/a5567dda-26fb-4e52-a8d6-1a8a9d70faa8

**Comment by marcusstenbeck** [comment]
Hm, it does seem like the components are only visible for one second of the three second clip you posted. Are you using Remotion v4?

**Comment by btahir** [comment]
Yes - its v4. It works as expected if I take out the third page so seems the logic is only setup for 2 pages.

**Comment by marcusstenbeck** [comment]
OK, thanks, I'll have to take a look at what has changed under the hood with v4. Thanks for reporting!

**Comment by btahir** [comment]
Ok - thanks! So to be clear you think this is a version issue and this code would work in the version you used?

**Comment by btahir** [comment]
Just saw Jonny added Remotion Transition so maybe this project won't need to be maintained standalone going forward. Still lots of cool stuff here that can hopefully be consolidated to the main repo. 

Would be cool to awesome effects like Camera Pan that were built out here to be added to the main package. :)

**Comment by marcusstenbeck** [comment]
Had a chat with Jonny and we decided to consolidate our efforts. You can consider this project deprecated!
